# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a83b98faca46a6de2ea998d52cee0be13c6291a9e45250f83e7fc86df9e0ec9506f6b3cffb124cad218292490a34f8ca759be6f76489e606151984212f07541

test:
  secret_key_base: 84dd6cd0d0b5d35c1b93046300faa538f33a5f01312ef68b77c5bcd066ad9d980f86ebedc547d3ae60e2804623f69d08298e2c8c1cf2f5201fe3f40a335e0a05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
